name: Scheduled Data Ingestion from Moveworks API

on:
  schedule:
    # This runs the workflow daily at 00:00 UTC (midnight).
    # Cron syntax: "minute hour day_of_month month day_of_week"
    #- cron: '15 15 * * *'
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the GitHub Actions tab.
    # It's very useful for testing and immediate runs.

jobs:
  ingest_data_job:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4 # Action to get your code into the runner environment

    - name: Set up Python environment
      uses: actions/setup-python@v5 # Action to set up Python
      with:
        python-version: '3.9' # Specify your desired Python version (e.g., '3.8', '3.10', '3.11')

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Installs libraries from your requirements.txt

    - name: Execute data ingestion script
      env:
        # Pass GitHub Secrets as environment variables to your script
        AZURE_USER: ${{ secrets.AZURE_USER }}
        AZURE_PW: ${{ secrets.AZURE_PW }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        TABLE_NAME: ${{ secrets.TABLE_NAME }}
        AZURE_HOST: ${{ secrets.AZURE_HOST }}
        AZURE_DB: ${{ secrets.AZURE_DB }}
        AZURE_PORT: ${{ secrets.AZURE_PORT }} # Only include if you created this secret
      run: |
        # Execute your Python script
        python test_ingestion.py
